# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  greetings:
    image: greetings
    build:
      context: .
      dockerfile: Demo2/services/greetings/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80:80"