# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  greetings:
    image: greetings
    build:
      context: .
      dockerfile: Demo2/services/greetings/Dockerfile
    ports:
      - 8084
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8084
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
